name: mapfree
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=11.1
  - pytorch=1.8.0
  - torchvision=0.9.0
  - pip
  - pip:
      - opencv-python>=4.5.3
      - open3d==0.14.1
      - transforms3d
      - yacs>=0.1.8
      - h5py
      - pytorch-lightning==1.6.5
      - kornia==0.5.3